import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {renderEvidence} from '../render.js';
test('isolated browser renders both roles, delivers state and blocks external fetch', {skip:process.env.BROWSER_TEST!=='1'},async()=>{
 const dir=await mkdtemp(join(tmpdir(),'rm-browser-'));
 try{
  const pack={manifest:{schemaVersion:1,id:'browser-test',version:'1.0.0',title:{en:'Browser test'},description:{en:'Compatibility test fixture'},author:'Manaty',license:'MIT',languages:['en'],players:{min:2,max:4},durationMinutes:15,runtime:'quickjs-v1',entry:'dist/game.rmg.json',permissions:[]},licenseText:'MIT license fixture '.repeat(10),assets:{},engine:`globalThis.RetroMuseumGame={create(players){return {status(){return {winner:null,requiredPlayers:players.map(p=>p.id)}},snapshot(){return {message:'Ready to play'}},save(){return {}},advance(){},action(){},release(){},addPlayer(){}}}}`,view:`<!doctype html><html><head></head><body><h1>Game is loading</h1><script>addEventListener('message',e=>{if(e.source!==parent)return;document.querySelector('h1').textContent=e.data.role+' '+e.data.state.party.community.message});fetch('https://example.com/forbidden').then(()=>{throw Error('External network unexpectedly accessible')}).catch(()=>{});parent.postMessage({retroMuseum:1,type:'ready'},'*');</script></body></html>`};
  const file=join(dir,'game.rmg.json');await writeFile(file,JSON.stringify(pack));const evidence=await renderEvidence(file);
  assert.equal(evidence.passed,true,JSON.stringify(evidence.failures||evidence.reason));assert.equal(evidence.screens.length,2);assert.match(evidence.screens[0].text,/display Ready to play/);assert.match(evidence.screens[1].text,/controller Ready to play/);
 }finally{await rm(dir,{recursive:true,force:true});}
});
