import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {declarations,publicationDecision,RULES,POLICY_VERSION} from '../policy.js';import {review} from '../review.js';import {Store} from '../storage.js';import {processSubmission,publishApproved} from '../pipeline.js';
const findings=result=>RULES.map(r=>({rule:r.id,result,reason:'Evidence reviewed.'}));
test('community packages cannot reserve an official game ID',async()=>{
 let wrote=false;await assert.rejects(publishApproved({manifest:{id:'chess'},source:{url:'https://github.com/outsider/chess'}},Buffer.from('{}'),{get:async()=>null,put:async()=>{wrote=true;}}),/reserved/);assert.equal(wrote,false);
});
test('the pipeline discards author or render-supplied attestations without a private matching record',async()=>{
 const values=new Map();const outbox={get:async k=>values.get(k)||null,put:async(k,v)=>values.set(k,v)};
 const report=await processSubmission({id:'fixture',source:{commit:'source'},declarations:{playthrough:{passed:true}}},{outbox,download:async()=>({bytes:Buffer.from('{}'),pack:{manifest:{id:'fixture'}},hash:'hash'}),validate:async()=>({status:'passed',sha256:'hash'}),fork:async()=>({url:'https://github.com/manaty/fixture'}),render:async()=>({passed:true,screens:[],playthrough:{passed:true}}),ai:async(pack,declarations,{evidence})=>{assert.equal(evidence.playthrough,null);return {status:'needs_review'};}});
 assert.equal(report.status,'needs_review');assert.equal(values.has('games/fixture.json'),false);
});
test('AI output cannot bypass missing evidence or invent policy findings',()=>{assert.equal(publicationDecision({findings:findings('pass')},{complete:false}),'needs_review');assert.equal(publicationDecision({findings:findings('pass')},{complete:true}),'approved');assert.equal(publicationDecision({findings:findings('reject')},{complete:true}),'rejected');assert.throws(()=>publicationDecision({findings:[{rule:'SEC-01',result:'pass',reason:'ok'}]},{complete:true}));});
test('declarations require affirmative current-policy acceptance',()=>{assert.throws(()=>declarations({policyVersion:'old'}));assert.throws(()=>declarations({policyVersion:POLICY_VERSION,rightsConfirmed:false}));});
test('missing AI key and incomplete response never approve',async()=>{const pack={assets:{},manifest:{},engine:'',view:'',licenseText:''};assert.equal((await review(pack,{}, {key:''})).status,'needs_review');await assert.rejects(review(pack,{}, {key:'test',fetcher:async()=>({ok:true,json:async()=>({status:'incomplete'})})}),/incomplete/);});
test('initial screenshots cannot approve untested gameplay; audio cannot be silently accepted',async()=>{
 const response={status:'completed',id:'test',output:[{content:[{type:'output_text',text:JSON.stringify({summary:'Reviewed fixture.',findings:findings('pass')})}]}]};
 const options={key:'test',evidence:{passed:true,screens:[{role:'display',text:'Game display',image:'test'},{role:'controller',text:'Controls',image:'test'}]},fetcher:async()=>({ok:true,json:async()=>response})};
 const pack={assets:{},manifest:{},engine:'',view:'',licenseText:''};const initial=await review(pack,{},options);assert.equal(initial.status,'needs_review');assert.equal(initial.coverage.complete,false);assert.equal(initial.findings.find(f=>f.rule==='QUALITY-01').result,'uncertain');
 assert.equal((await review(pack,{playthrough:{passed:true}},options)).status,'needs_review','author declarations cannot provide trusted playthrough evidence');
 assert.equal((await review(pack,{}, {...options,evidence:{...options.evidence,playthrough:{reviewer:{kind:'agent'},scope:'Trusted test fixture supplied by the private pipeline'}}})).status,'approved');
 pack.assets['voice.mp3']={type:'audio/mpeg',data:'test'};const result=await review(pack,{},options);assert.equal(result.status,'needs_review');assert.equal(result.findings.find(f=>f.rule==='SAFE-01').result,'uncertain');
});
test('approved exact artifact is published only after validation, fork and complete editorial evidence',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'rm-approved-'));try{const outbox=new Store(null,dir);const bytes=Buffer.from('{"verified":true}');const result=await processSubmission({id:'accepted',source:{fullName:'author/game'},submittedAt:'now'},{outbox,download:async()=>({bytes,pack:{manifest:{id:'approved-game'}},hash:'trustedhash'}),validate:async()=>({status:'passed',sha256:'trustedhash'}),fork:async()=>({url:'https://github.com/manaty/rm-author-game'}),render:async()=>({passed:true,screens:[]}),ai:async()=>({status:'approved',coverage:{complete:true}})});assert.equal(result.status,'approved');assert.equal((await outbox.get('games/approved-game.json')).sha256,'trustedhash');assert.deepEqual(await outbox.bytes('packages/trustedhash.json'),bytes);}finally{await rm(dir,{recursive:true,force:true});}
});
test('independent failed validation prevents fork, AI and publication',async()=>{const dir=await mkdtemp(join(tmpdir(),'rm-pipeline-'));try{const outbox=new Store(null,dir);let forked=false,reviewed=false;const result=await processSubmission({id:'abc',source:{fullName:'a/b'},submittedAt:'now'},{outbox,download:async()=>({bytes:Buffer.from('{}'),pack:{manifest:{id:'test'}},hash:'hash'}),validate:async()=>({status:'failed'}),fork:async()=>{forked=true},ai:async()=>{reviewed=true}});assert.equal(result.status,'rejected');assert.equal(forked,false);assert.equal(reviewed,false);assert.deepEqual(await outbox.list('games/'),[]);}finally{await rm(dir,{recursive:true,force:true});}});
test('incomplete AI approval is held after fork and cannot enter catalog',async()=>{const dir=await mkdtemp(join(tmpdir(),'rm-pipeline-'));try{const outbox=new Store(null,dir);const order=[];const result=await processSubmission({id:'abc',source:{fullName:'a/b'},submittedAt:'now'},{outbox,download:async()=>({bytes:Buffer.from('{}'),pack:{manifest:{id:'test'}},hash:'hash'}),validate:async()=>{order.push('validate');return {status:'passed',sha256:'hash'}},fork:async()=>{order.push('fork');return {url:'https://github.com/manaty/rm-a-b'}},ai:async()=>{order.push('ai');return {status:'approved',coverage:{complete:false}}}});assert.equal(result.status,'needs_review');assert.deepEqual(order,['validate','fork','ai']);assert.deepEqual(await outbox.list('games/'),[]);}finally{await rm(dir,{recursive:true,force:true});}});
